### ISSUE TITLE
ArrayIndexOutOfBoundsException in LzoDecompressor1z

### ISSUE THREAD

**Issue by rishi-089** [shevek/lzo-java#10]
Hi,

 LzoDecompressor1z ld = new LzoDecompressor1z();
            ld.decompress(packet.getData(),  0, packet.getLength(), o_buf, 0, new lzo_uintp());

is giving following error. Plz help

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1786

Thanks In Advance

**Comment by shevek** [comment]
Without knowing more about how your packet was constructed or what data is in it, I probably can't help.
