### ISSUE TITLE
Is that compatible with lzo 2.09

### ISSUE THREAD

**Issue by XuNeal** [shevek/lzo-java#5]
Hey

I want to know if this is compatible with lzo 2.09?

**Comment by shevek** [comment]
I think the definition of the compression algorithms is fixed, and the only recent fixes in the LZO library were related to memory overflows, which don't affect the Java implementation. So a fairly firm guess is "yes", but if you have any issues, please submit a sample and I'll fix and integrate into tests.

**Comment by ronakvorabr** [comment]
Hm, if it should work with 2.0.9 then 

https://github.com/shevek/lzo-java/blob/874afe5f97789216a5f0d7d81b55a9bf2550b8bb/lzo-core/src/main/jcpp/include/lzo/lzoconf.h

should be updated, correct? 

I'd be happy to do this. Let me know if I'm thinking correctly.
